language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    # Don't compile with gcc on MacOS
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - subversion
    - g++
    - xterm
    - libfltk1.3-dev
    - freeglut3-dev
    - libpng12-dev
    - libjpeg-dev
    - libxft-dev
    - libxinerama-dev
    - libtiff4-dev
    - tree
  homebrew:
    packages:
    - fltk
    - jpeg
    - libpng
    - libtiff

script:
  - ./build-moos.sh
  - ./build-ivp.sh
