name: CMake Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            os-type: debian
          - os: macos-14
            os-type: darwin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies - Debian/Ubuntu
      if: matrix.os-type == 'debian'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake build-essential git libtiff5-dev libfltk1.3-dev freeglut3-dev libpng-dev libjpeg-dev libxinerama-dev libxft-dev

    - name: Install Homebrew
      if: matrix.os-type == 'darwin'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        
    - name: Install Dependencies - Mac OS X
      if: matrix.os-type == 'darwin'
      run: |
         brew update
         brew install fltk libtiff autoconf automake
         
    
    - name: Build
      # Build your program with the given configuration
      run: ./build.sh

    - name: Check build
      run: ./build-check.sh
      

